// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh-HK'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	structural: {
		header: {
			/**
			 * F​i​l​e
			 */
			file_menu: string
			/**
			 * O​p​e​n
			 */
			file_open: string
			/**
			 * C​l​o​s​e
			 */
			file_close: string
			/**
			 * S​a​v​e
			 */
			file_save: string
			/**
			 * S​a​v​e​ ​A​s
			 */
			file_save_as: string
			/**
			 * E​x​p​o​r​t
			 */
			file_export_submenu: string
			/**
			 * E​x​p​o​r​t​ ​t​o​ ​M​a​r​k​d​o​w​n
			 */
			file_export_md: string
			/**
			 * E​x​p​o​r​t​ ​t​o​ ​T​e​x​t​ ​(​T​O​D​O​)
			 */
			file_export_txt: string
			/**
			 * S​e​t​t​i​n​g
			 */
			setting_menu: string
			/**
			 * E​d​i​t
			 */
			edit_menu: string
			/**
			 * U​n​d​o
			 */
			edit_undo: string
			/**
			 * R​e​d​o
			 */
			edit_redo: string
			/**
			 * W​i​n​d​o​w
			 */
			window_menu: string
			/**
			 * N​e​w​ ​W​i​n​d​o​w
			 */
			window_new: string
		}
		file: {
			/**
			 * F​i​l​e
			 */
			title: string
			/**
			 * N​o​t​e
			 */
			note: string
			/**
			 * C​r​e​a​t​e​ ​N​o​t​e
			 */
			create_note: string
			/**
			 * O​p​e​n​ ​E​x​i​s​t​i​n​g​ ​N​o​t​e
			 */
			open_existing_note: string
			/**
			 * F​i​l​e​n​a​m​e
			 */
			filename: string
			/**
			 * N​o​t​e​ ​N​a​m​e
			 */
			note_name: string
			/**
			 * U​n​t​i​t​l​e​d
			 */
			untitled: string
			/**
			 * S​a​v​e​d
			 */
			saved: string
			'export': {
				/**
				 * E​x​p​o​r​t
				 */
				'export': string
				/**
				 * P​r​e​v​i​e​w​ ​e​x​p​o​r​t​ ​f​i​l​e​:
				 */
				preview_title: string
			}
		}
		template: {
			/**
			 * T​e​m​p​l​a​t​e
			 */
			template: string
			/**
			 * S​e​l​e​c​t​ ​A​ ​T​e​m​p​l​a​t​e
			 */
			select_template: string
			/**
			 * B​l​a​n​k
			 */
			blank: string
			/**
			 * T​u​t​o​r​i​a​l
			 */
			tutorial: string
		}
		section: {
			/**
			 * S​e​c​t​i​o​n
			 */
			section: string
			/**
			 * A​d​d​ ​S​e​c​t​i​o​n
			 */
			add_section: string
			/**
			 * A​d​d​ ​T​e​x​t​ ​S​e​c​t​i​o​n
			 */
			add_text_section: string
			/**
			 * A​d​d​ ​S​t​r​u​c​t​u​r​a​l​ ​S​e​c​t​i​o​n
			 */
			add_struct_section: string
			/**
			 * A​d​d​ ​D​e​f​i​n​i​t​i​o​n
			 */
			add_section_definition: string
			/**
			 * N​e​w​ ​S​e​c​t​i​o​n
			 */
			new_section_default_title: string
		}
		element: {
			/**
			 * E​l​e​m​e​n​t
			 */
			element: string
			/**
			 * A​d​d​ ​E​l​e​m​e​n​t
			 */
			add_element: string
			/**
			 * A​d​d​ ​T​e​x​t​ ​E​l​e​m​e​n​t
			 */
			add_text_element: string
			/**
			 * A​d​d​ ​M​a​r​k​d​o​w​n​ ​E​l​e​m​e​n​t
			 */
			add_markdown_element: string
			/**
			 * A​d​d​ ​S​t​r​u​c​t​u​r​a​l​ ​E​l​e​m​e​n​t
			 */
			add_struct_element: string
		}
		struct_def: {
			/**
			 * S​e​c​t​i​o​n​ ​D​e​f​i​n​i​t​i​o​n
			 */
			section_def_title: string
			/**
			 * A​t​t​r​i​b​u​t​e​s
			 */
			attributes_tab_title: string
			/**
			 * D​i​s​p​l​a​y​ ​N​a​m​e
			 */
			display_name_tab_title: string
			/**
			 * S​e​p​a​r​a​t​o​r
			 */
			display_name_separator_label: string
			/**
			 * N​a​m​e
			 */
			display_name_table_name_col: string
			/**
			 * A​c​t​i​o​n
			 */
			display_name_table_action_col: string
			/**
			 * N​a​m​e
			 */
			attr_table_name_col: string
			/**
			 * T​y​p​e
			 */
			attr_table_type_col: string
			/**
			 * D​e​s​c​r​i​p​t​i​o​n
			 */
			attr_table_description_col: string
			/**
			 * A​c​t​i​o​n
			 */
			attr_table_action_col: string
			/**
			 * B​a​s​i​c
			 */
			edit_attr_basic_tab_title: string
			/**
			 * T​y​p​e
			 */
			edit_attr_type_tab_title: string
			/**
			 * N​a​m​e
			 */
			edit_attr_basic_name_label: string
			/**
			 * D​e​s​c​r​i​p​t​i​o​n
			 */
			edit_attr_basic_description_label: string
			/**
			 * D​e​f​a​u​l​t​ ​V​a​l​u​e
			 */
			edit_attr_constraint_default_label: string
			/**
			 * C​h​o​o​s​e​ ​A​t​t​r​i​b​u​t​e​ ​T​y​p​e
			 */
			edit_attr_choose_type_label: string
			/**
			 * D​e​f​i​n​i​t​i​o​n​ ​U​p​d​a​t​e​d
			 */
			update_attr_def_confirm: string
			/**
			 * I​n​v​a​l​i​d​ ​{​t​a​r​g​e​t​}​ ​D​e​f​i​n​i​t​i​o​n
			 * @param {string} target
			 */
			invalid_definition: RequiredParams<'target'>
		}
		attribute: {
			/**
			 * A​t​t​r​i​b​u​t​e
			 */
			attribute: string
			type: {
				/**
				 * T​y​p​e
				 */
				type: string
				/**
				 * T​e​x​t
				 */
				string: string
				/**
				 * L​o​n​g​ ​T​e​x​t
				 */
				long_string: string
				/**
				 * I​n​t​e​g​e​r
				 */
				int: string
				/**
				 * B​o​o​l​e​a​n
				 */
				boolean: string
				/**
				 * D​e​c​i​m​a​l
				 */
				decimal: string
				/**
				 * M​a​r​k​d​o​w​n
				 */
				markdown: string
			}
			constraint: {
				/**
				 * C​o​n​s​t​r​a​i​n​t
				 */
				constraint: string
				/**
				 * R​e​q​u​i​r​e​d
				 */
				require: string
				/**
				 * U​n​i​q​u​e
				 */
				unique: string
				/**
				 * M​i​n​i​m​u​m
				 */
				min: string
				/**
				 * M​a​x​i​m​u​m
				 */
				max: string
				/**
				 * P​a​t​t​e​r​n​ ​(​R​e​g​e​x​)
				 */
				regex: string
				param: {
					/**
					 * (​i​n​c​l​u​s​i​v​e​)
					 */
					inclusive_label: string
				}
				error: {
					/**
					 * T​h​e​ ​m​i​n​i​m​u​m​ ​v​a​l​u​e​ ​i​s​ ​n​o​t​ ​s​e​t​.
					 */
					min_val_is_null: string
					/**
					 * T​h​e​ ​m​a​x​i​m​u​m​ ​v​a​l​u​e​ ​i​s​ ​n​o​t​ ​s​e​t​.
					 */
					max_val_is_null: string
					/**
					 * V​a​l​u​e​ ​<​ ​m​i​n​i​m​u​m
					 */
					val_less_than_min: string
					/**
					 * V​a​l​u​e​ ​>​ ​m​a​x​i​m​u​m
					 */
					val_larger_than_max: string
					/**
					 * V​a​l​u​e​ ​i​s​ ​d​u​p​l​i​c​a​t​e​d
					 */
					val_not_unique: string
					/**
					 * T​h​i​s​ ​a​t​t​r​i​b​u​t​e​ ​i​s​ ​r​e​q​u​i​r​e​d
					 */
					attr_is_required: string
				}
			}
			value: {
				/**
				 * D​o​u​b​l​e​ ​c​l​i​c​k​ ​t​o​ ​e​d​i​t
				 */
				double_click_to_edit: string
			}
			error: {
				/**
				 * T​h​e​r​e​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​a​t​t​r​i​b​u​t​e​ ​d​e​f​i​n​i​t​i​o​n​.
				 */
				no_attr: string
				/**
				 * A​t​t​r​i​b​u​t​e​ ​n​a​m​e​ ​c​a​n​n​o​t​ ​b​e​ ​e​m​p​t​y​.
				 */
				empty_attr_name: string
				/**
				 * A​t​t​r​i​b​u​t​e​ ​t​y​p​e​ ​c​a​n​n​o​t​ ​b​e​ ​e​m​p​t​y​ ​f​o​r​ ​a​t​t​r​i​b​u​t​e​ ​'​{​n​a​m​e​}​'​.
				 * @param {string} name
				 */
				empty_attr_type: RequiredParams<'name'>
				/**
				 * T​h​e​ ​a​t​t​r​i​b​u​t​e​ ​n​a​m​e​ ​'​{​n​a​m​e​}​'​ ​i​s​ ​n​o​t​ ​u​n​i​q​u​e​.
				 * @param {string} name
				 */
				attr_name_duplicated: RequiredParams<'name'>
				/**
				 * I​n​v​a​l​i​d​ ​v​a​l​u​e​ ​f​o​r​ ​a​t​t​r​i​b​u​t​e​ ​'​{​a​t​t​r​_​n​a​m​e​}​'​:
				 * @param {string} attr_name
				 */
				invalid_value_for_attr: RequiredParams<'attr_name'>
				/**
				 * I​n​v​a​l​i​d​ ​d​e​f​a​u​l​t​ ​v​a​l​u​e​ ​f​o​r​ ​a​t​t​r​i​b​u​t​e​ ​'​{​a​t​t​r​_​n​a​m​e​}​'​:
				 * @param {string} attr_name
				 */
				invalid_default_value_for_attr: RequiredParams<'attr_name'>
				/**
				 * C​o​n​s​t​r​a​i​n​t​ ​'​{​c​o​n​s​t​r​a​i​n​t​}​'​ ​f​o​r​ ​a​t​t​r​i​b​u​t​e​ ​'​{​a​t​t​r​_​n​a​m​e​}​'​ ​i​s​ ​i​n​v​a​l​i​d​:
				 * @param {string} attr_name
				 * @param {string} constraint
				 */
				invalid_constraint_for_attr: RequiredParams<'attr_name' | 'constraint'>
				/**
				 * C​o​n​s​t​r​a​i​n​t​ ​'​{​c​o​n​s​t​r​a​i​n​t​_​a​}​'​ ​i​s​ ​n​o​t​ ​c​o​m​p​a​t​i​b​l​e​ ​t​o​ ​c​o​n​s​t​r​a​i​n​t​ ​{​c​o​n​s​t​r​a​i​n​t​_​b​}​ ​f​o​r​ ​a​t​t​r​i​b​u​t​e​ ​'​{​a​t​t​r​_​n​a​m​e​}​'
				 * @param {string} attr_name
				 * @param {string} constraint_a
				 * @param {string} constraint_b
				 */
				incompatible_constraint_for_attr: RequiredParams<'attr_name' | 'constraint_a' | 'constraint_b'>
			}
		}
		setting: {
			/**
			 * S​e​t​t​i​n​g
			 */
			title: string
			/**
			 * L​a​n​g​u​a​g​e
			 */
			lang: string
			save_before: {
				/**
				 * S​a​v​e​ ​t​h​e​ ​n​o​t​e​ ​b​e​f​o​r​e​ ​u​p​d​a​t​i​n​g​ ​t​h​e​ ​s​e​t​t​i​n​g​.
				 */
				content: string
			}
		}
	}
	common: {
		/**
		 * C​o​n​f​i​r​m
		 */
		confirm: string
		save_confirm_window: {
			/**
			 * S​a​v​e​ ​{​t​a​r​g​e​t​}
			 * @param {string} target
			 */
			title: RequiredParams<'target'>
			/**
			 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​s​a​v​e​ ​t​h​e​ ​c​h​a​n​g​e​s​?
			 */
			content: string
			/**
			 * S​a​v​e
			 */
			save: string
			/**
			 * D​o​n​'​t​ ​S​a​v​e
			 */
			do_not_save: string
		}
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * S​u​c​c​e​s​s
		 */
		success: string
		/**
		 * S​a​v​e​d
		 */
		saved: string
		/**
		 * A​d​d
		 */
		add: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * E​r​r​o​r
		 */
		error: string
		/**
		 * L​o​a​d​i​n​g​.​.​.
		 */
		loading: string
	}
	symbol: {
		/**
		 * :
		 */
		colon: string
	}
	error: {
		general: {
			/**
			 * E​r​r​o​r
			 */
			title: string
			/**
			 * F​a​i​l​ ​t​o​ ​o​p​e​n​ ​n​o​t​e​.
			 */
			open_note: string
			/**
			 * F​a​i​l​ ​t​o​ ​o​p​e​n​ ​n​o​t​e​.
			 */
			create_note: string
			/**
			 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​.
			 */
			message: string
			unsupported: {
				/**
				 * U​n​s​u​p​p​o​r​t​e​d​ ​o​p​e​r​a​t​i​o​n
				 */
				title: string
				/**
				 * O​p​e​r​a​t​i​o​n​ ​'​{​0​}​'​ ​n​o​t​ ​i​m​p​l​e​m​e​n​t​e​d​ ​o​r​ ​n​o​t​ ​s​u​p​p​o​r​t​e​d​.
				 * @param {unknown} 0
				 */
				message: RequiredParams<'0'>
			}
		}
		attribute: {
			invalid_type_conversion: {
				/**
				 * I​n​v​a​l​i​d​ ​T​y​p​e​ ​C​o​n​v​e​r​s​i​o​n
				 */
				title: string
				/**
				 * C​a​n​n​o​t​ ​c​o​n​v​e​r​t​ ​d​a​t​a​ ​f​r​o​m​ ​t​y​p​e​ ​{​0​}​ ​t​o​ ​t​y​p​e​ ​{​1​}​.
				 * @param {unknown} 0
				 * @param {unknown} 1
				 */
				message: RequiredParams<'0' | '1'>
			}
			null_attr_type: {
				/**
				 * N​u​l​l​ ​A​t​t​r​i​b​u​t​e​ ​T​y​p​e
				 */
				title: string
				/**
				 * A​t​t​r​i​b​u​t​e​ ​T​y​p​e​ ​c​a​n​n​o​t​ ​b​e​ ​n​u​l​l​.
				 */
				message: string
			}
			incompatible_constraint: {
				/**
				 * I​n​c​o​m​p​a​t​i​b​l​e​ ​C​o​n​s​t​r​a​i​n​t
				 */
				title: string
				/**
				 * N​e​w​ ​{​0​}​ ​c​o​n​s​t​r​a​i​n​t​ ​n​o​t​ ​c​o​m​p​a​t​i​b​l​e​ ​t​o​ ​e​x​i​s​t​i​n​g​ ​{​1​}​ ​c​o​n​s​t​r​a​i​n​t​.
				 * @param {unknown} 0
				 * @param {unknown} 1
				 */
				message: RequiredParams<'0' | '1'>
			}
			forbidden_constraint: {
				/**
				 * F​o​r​b​i​d​d​e​n​ ​C​o​n​s​t​r​a​i​n​t
				 */
				title: string
				/**
				 * {​0​}​ ​c​o​n​s​t​r​a​i​n​t​ ​i​s​ ​n​o​t​ ​a​l​l​o​w​e​d​ ​f​o​r​ ​t​h​i​s​ ​a​t​t​r​i​b​u​t​e​.
				 * @param {unknown} 0
				 */
				message: RequiredParams<'0'>
			}
		}
		conversion: {
			invalid_json_format: {
				/**
				 * I​n​v​a​l​i​d​ ​J​S​O​N​ ​F​o​r​m​a​t
				 */
				title: string
				/**
				 * F​a​i​l​ ​t​o​ ​p​a​r​s​e​ ​{​0​}​ ​f​r​o​m​ ​j​s​o​n​.
				 * @param {unknown} 0
				 */
				message: RequiredParams<'0'>
			}
			invalid_data: {
				/**
				 * I​n​v​a​l​i​d​ ​D​a​t​a
				 */
				title: string
				/**
				 * F​a​i​l​ ​t​o​ ​p​a​r​s​e​ ​{​0​}​ ​d​u​e​ ​t​o​ ​i​n​v​a​l​i​d​ ​d​a​t​a​.
				 * @param {unknown} 0
				 */
				message: RequiredParams<'0'>
			}
		}
		file: {
			invalid_path: {
				/**
				 * I​n​v​a​l​i​d​ ​F​i​l​e​ ​P​a​t​h
				 */
				title: string
				/**
				 * T​h​e​ ​f​i​l​e​ ​p​a​t​h​ ​i​s​ ​i​n​v​a​l​i​d​.
				 */
				message: string
			}
			already_opened: {
				/**
				 * F​i​l​e​ ​A​l​r​e​a​d​y​ ​O​p​e​n​e​d
				 */
				title: string
				/**
				 * T​h​e​ ​f​i​l​e​ ​'​{​0​}​'​ ​i​s​ ​a​l​r​e​a​d​y​ ​o​p​e​n​e​d​ ​i​n​ ​s​o​m​e​ ​w​i​n​d​o​w​.
				 * @param {unknown} 0
				 */
				message: RequiredParams<'0'>
			}
			io: {
				/**
				 * F​i​l​e​ ​I​O​ ​E​r​r​o​r
				 */
				title: string
				/**
				 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​w​h​e​n​ ​a​c​c​e​s​s​i​n​g​ ​t​h​e​ ​f​i​l​e​.
				 */
				message: string
			}
		}
	}
	test: {
		/**
		 * H​e​l​l​o​!
		 */
		no_parameter: string
		/**
		 * H​e​l​l​o​ ​{​n​a​m​e​}​!
		 * @param {string} name
		 */
		named_parameter: RequiredParams<'name'>
		/**
		 * H​e​l​l​o​ ​{​f​i​r​s​t​_​n​a​m​e​}​ ​{​l​a​s​t​_​n​a​m​e​}​!
		 * @param {string} first_name
		 * @param {string} last_name
		 */
		named_parameter2: RequiredParams<'first_name' | 'last_name'>
		/**
		 * H​e​l​l​o​ ​{​0​}​ ​{​1​}​!
		 * @param {unknown} 0
		 * @param {unknown} 1
		 */
		numbered_parameter: RequiredParams<'0' | '1'>
		/**
		 * H​e​l​l​o​ ​{​1​}​ ​{​0​}​!
		 * @param {unknown} 0
		 * @param {unknown} 1
		 */
		numbered_parameter2: RequiredParams<'0' | '1'>
	}
}

export type TranslationFunctions = {
	structural: {
		header: {
			/**
			 * File
			 */
			file_menu: () => LocalizedString
			/**
			 * Open
			 */
			file_open: () => LocalizedString
			/**
			 * Close
			 */
			file_close: () => LocalizedString
			/**
			 * Save
			 */
			file_save: () => LocalizedString
			/**
			 * Save As
			 */
			file_save_as: () => LocalizedString
			/**
			 * Export
			 */
			file_export_submenu: () => LocalizedString
			/**
			 * Export to Markdown
			 */
			file_export_md: () => LocalizedString
			/**
			 * Export to Text (TODO)
			 */
			file_export_txt: () => LocalizedString
			/**
			 * Setting
			 */
			setting_menu: () => LocalizedString
			/**
			 * Edit
			 */
			edit_menu: () => LocalizedString
			/**
			 * Undo
			 */
			edit_undo: () => LocalizedString
			/**
			 * Redo
			 */
			edit_redo: () => LocalizedString
			/**
			 * Window
			 */
			window_menu: () => LocalizedString
			/**
			 * New Window
			 */
			window_new: () => LocalizedString
		}
		file: {
			/**
			 * File
			 */
			title: () => LocalizedString
			/**
			 * Note
			 */
			note: () => LocalizedString
			/**
			 * Create Note
			 */
			create_note: () => LocalizedString
			/**
			 * Open Existing Note
			 */
			open_existing_note: () => LocalizedString
			/**
			 * Filename
			 */
			filename: () => LocalizedString
			/**
			 * Note Name
			 */
			note_name: () => LocalizedString
			/**
			 * Untitled
			 */
			untitled: () => LocalizedString
			/**
			 * Saved
			 */
			saved: () => LocalizedString
			'export': {
				/**
				 * Export
				 */
				'export': () => LocalizedString
				/**
				 * Preview export file:
				 */
				preview_title: () => LocalizedString
			}
		}
		template: {
			/**
			 * Template
			 */
			template: () => LocalizedString
			/**
			 * Select A Template
			 */
			select_template: () => LocalizedString
			/**
			 * Blank
			 */
			blank: () => LocalizedString
			/**
			 * Tutorial
			 */
			tutorial: () => LocalizedString
		}
		section: {
			/**
			 * Section
			 */
			section: () => LocalizedString
			/**
			 * Add Section
			 */
			add_section: () => LocalizedString
			/**
			 * Add Text Section
			 */
			add_text_section: () => LocalizedString
			/**
			 * Add Structural Section
			 */
			add_struct_section: () => LocalizedString
			/**
			 * Add Definition
			 */
			add_section_definition: () => LocalizedString
			/**
			 * New Section
			 */
			new_section_default_title: () => LocalizedString
		}
		element: {
			/**
			 * Element
			 */
			element: () => LocalizedString
			/**
			 * Add Element
			 */
			add_element: () => LocalizedString
			/**
			 * Add Text Element
			 */
			add_text_element: () => LocalizedString
			/**
			 * Add Markdown Element
			 */
			add_markdown_element: () => LocalizedString
			/**
			 * Add Structural Element
			 */
			add_struct_element: () => LocalizedString
		}
		struct_def: {
			/**
			 * Section Definition
			 */
			section_def_title: () => LocalizedString
			/**
			 * Attributes
			 */
			attributes_tab_title: () => LocalizedString
			/**
			 * Display Name
			 */
			display_name_tab_title: () => LocalizedString
			/**
			 * Separator
			 */
			display_name_separator_label: () => LocalizedString
			/**
			 * Name
			 */
			display_name_table_name_col: () => LocalizedString
			/**
			 * Action
			 */
			display_name_table_action_col: () => LocalizedString
			/**
			 * Name
			 */
			attr_table_name_col: () => LocalizedString
			/**
			 * Type
			 */
			attr_table_type_col: () => LocalizedString
			/**
			 * Description
			 */
			attr_table_description_col: () => LocalizedString
			/**
			 * Action
			 */
			attr_table_action_col: () => LocalizedString
			/**
			 * Basic
			 */
			edit_attr_basic_tab_title: () => LocalizedString
			/**
			 * Type
			 */
			edit_attr_type_tab_title: () => LocalizedString
			/**
			 * Name
			 */
			edit_attr_basic_name_label: () => LocalizedString
			/**
			 * Description
			 */
			edit_attr_basic_description_label: () => LocalizedString
			/**
			 * Default Value
			 */
			edit_attr_constraint_default_label: () => LocalizedString
			/**
			 * Choose Attribute Type
			 */
			edit_attr_choose_type_label: () => LocalizedString
			/**
			 * Definition Updated
			 */
			update_attr_def_confirm: () => LocalizedString
			/**
			 * Invalid {target} Definition
			 */
			invalid_definition: (arg: { target: string }) => LocalizedString
		}
		attribute: {
			/**
			 * Attribute
			 */
			attribute: () => LocalizedString
			type: {
				/**
				 * Type
				 */
				type: () => LocalizedString
				/**
				 * Text
				 */
				string: () => LocalizedString
				/**
				 * Long Text
				 */
				long_string: () => LocalizedString
				/**
				 * Integer
				 */
				int: () => LocalizedString
				/**
				 * Boolean
				 */
				boolean: () => LocalizedString
				/**
				 * Decimal
				 */
				decimal: () => LocalizedString
				/**
				 * Markdown
				 */
				markdown: () => LocalizedString
			}
			constraint: {
				/**
				 * Constraint
				 */
				constraint: () => LocalizedString
				/**
				 * Required
				 */
				require: () => LocalizedString
				/**
				 * Unique
				 */
				unique: () => LocalizedString
				/**
				 * Minimum
				 */
				min: () => LocalizedString
				/**
				 * Maximum
				 */
				max: () => LocalizedString
				/**
				 * Pattern (Regex)
				 */
				regex: () => LocalizedString
				param: {
					/**
					 * (inclusive)
					 */
					inclusive_label: () => LocalizedString
				}
				error: {
					/**
					 * The minimum value is not set.
					 */
					min_val_is_null: () => LocalizedString
					/**
					 * The maximum value is not set.
					 */
					max_val_is_null: () => LocalizedString
					/**
					 * Value < minimum
					 */
					val_less_than_min: () => LocalizedString
					/**
					 * Value > maximum
					 */
					val_larger_than_max: () => LocalizedString
					/**
					 * Value is duplicated
					 */
					val_not_unique: () => LocalizedString
					/**
					 * This attribute is required
					 */
					attr_is_required: () => LocalizedString
				}
			}
			value: {
				/**
				 * Double click to edit
				 */
				double_click_to_edit: () => LocalizedString
			}
			error: {
				/**
				 * There must be at least one attribute definition.
				 */
				no_attr: () => LocalizedString
				/**
				 * Attribute name cannot be empty.
				 */
				empty_attr_name: () => LocalizedString
				/**
				 * Attribute type cannot be empty for attribute '{name}'.
				 */
				empty_attr_type: (arg: { name: string }) => LocalizedString
				/**
				 * The attribute name '{name}' is not unique.
				 */
				attr_name_duplicated: (arg: { name: string }) => LocalizedString
				/**
				 * Invalid value for attribute '{attr_name}':
				 */
				invalid_value_for_attr: (arg: { attr_name: string }) => LocalizedString
				/**
				 * Invalid default value for attribute '{attr_name}':
				 */
				invalid_default_value_for_attr: (arg: { attr_name: string }) => LocalizedString
				/**
				 * Constraint '{constraint}' for attribute '{attr_name}' is invalid:
				 */
				invalid_constraint_for_attr: (arg: { attr_name: string, constraint: string }) => LocalizedString
				/**
				 * Constraint '{constraint_a}' is not compatible to constraint {constraint_b} for attribute '{attr_name}'
				 */
				incompatible_constraint_for_attr: (arg: { attr_name: string, constraint_a: string, constraint_b: string }) => LocalizedString
			}
		}
		setting: {
			/**
			 * Setting
			 */
			title: () => LocalizedString
			/**
			 * Language
			 */
			lang: () => LocalizedString
			save_before: {
				/**
				 * Save the note before updating the setting.
				 */
				content: () => LocalizedString
			}
		}
	}
	common: {
		/**
		 * Confirm
		 */
		confirm: () => LocalizedString
		save_confirm_window: {
			/**
			 * Save {target}
			 */
			title: (arg: { target: string }) => LocalizedString
			/**
			 * Do you want to save the changes?
			 */
			content: () => LocalizedString
			/**
			 * Save
			 */
			save: () => LocalizedString
			/**
			 * Don't Save
			 */
			do_not_save: () => LocalizedString
		}
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Success
		 */
		success: () => LocalizedString
		/**
		 * Saved
		 */
		saved: () => LocalizedString
		/**
		 * Add
		 */
		add: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Error
		 */
		error: () => LocalizedString
		/**
		 * Loading...
		 */
		loading: () => LocalizedString
	}
	symbol: {
		/**
		 * :
		 */
		colon: () => LocalizedString
	}
	error: {
		general: {
			/**
			 * Error
			 */
			title: () => LocalizedString
			/**
			 * Fail to open note.
			 */
			open_note: () => LocalizedString
			/**
			 * Fail to open note.
			 */
			create_note: () => LocalizedString
			/**
			 * Something went wrong.
			 */
			message: () => LocalizedString
			unsupported: {
				/**
				 * Unsupported operation
				 */
				title: () => LocalizedString
				/**
				 * Operation '{0}' not implemented or not supported.
				 */
				message: (arg0: unknown) => LocalizedString
			}
		}
		attribute: {
			invalid_type_conversion: {
				/**
				 * Invalid Type Conversion
				 */
				title: () => LocalizedString
				/**
				 * Cannot convert data from type {0} to type {1}.
				 */
				message: (arg0: unknown, arg1: unknown) => LocalizedString
			}
			null_attr_type: {
				/**
				 * Null Attribute Type
				 */
				title: () => LocalizedString
				/**
				 * Attribute Type cannot be null.
				 */
				message: () => LocalizedString
			}
			incompatible_constraint: {
				/**
				 * Incompatible Constraint
				 */
				title: () => LocalizedString
				/**
				 * New {0} constraint not compatible to existing {1} constraint.
				 */
				message: (arg0: unknown, arg1: unknown) => LocalizedString
			}
			forbidden_constraint: {
				/**
				 * Forbidden Constraint
				 */
				title: () => LocalizedString
				/**
				 * {0} constraint is not allowed for this attribute.
				 */
				message: (arg0: unknown) => LocalizedString
			}
		}
		conversion: {
			invalid_json_format: {
				/**
				 * Invalid JSON Format
				 */
				title: () => LocalizedString
				/**
				 * Fail to parse {0} from json.
				 */
				message: (arg0: unknown) => LocalizedString
			}
			invalid_data: {
				/**
				 * Invalid Data
				 */
				title: () => LocalizedString
				/**
				 * Fail to parse {0} due to invalid data.
				 */
				message: (arg0: unknown) => LocalizedString
			}
		}
		file: {
			invalid_path: {
				/**
				 * Invalid File Path
				 */
				title: () => LocalizedString
				/**
				 * The file path is invalid.
				 */
				message: () => LocalizedString
			}
			already_opened: {
				/**
				 * File Already Opened
				 */
				title: () => LocalizedString
				/**
				 * The file '{0}' is already opened in some window.
				 */
				message: (arg0: unknown) => LocalizedString
			}
			io: {
				/**
				 * File IO Error
				 */
				title: () => LocalizedString
				/**
				 * Something went wrong when accessing the file.
				 */
				message: () => LocalizedString
			}
		}
	}
	test: {
		/**
		 * Hello!
		 */
		no_parameter: () => LocalizedString
		/**
		 * Hello {name}!
		 */
		named_parameter: (arg: { name: string }) => LocalizedString
		/**
		 * Hello {first_name} {last_name}!
		 */
		named_parameter2: (arg: { first_name: string, last_name: string }) => LocalizedString
		/**
		 * Hello {0} {1}!
		 */
		numbered_parameter: (arg0: unknown, arg1: unknown) => LocalizedString
		/**
		 * Hello {1} {0}!
		 */
		numbered_parameter2: (arg0: unknown, arg1: unknown) => LocalizedString
	}
}

export type Formatters = {}
