// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh-HK'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	structural: {
		/**
		 * C​r​e​a​t​e​ ​n​o​t​e
		 */
		CREATE_NOTE: string
	}
	test: {
		/**
		 * H​e​l​l​o​!
		 */
		no_parameter: string
		/**
		 * H​e​l​l​o​ ​{​n​a​m​e​}​!
		 * @param {string} name
		 */
		named_parameter: RequiredParams<'name'>
		/**
		 * H​e​l​l​o​ ​{​f​i​r​s​t​_​n​a​m​e​}​ ​{​l​a​s​t​_​n​a​m​e​}​!
		 * @param {string} first_name
		 * @param {string} last_name
		 */
		named_parameter2: RequiredParams<'first_name' | 'last_name'>
		/**
		 * H​e​l​l​o​ ​{​0​}​ ​{​1​}​!
		 * @param {unknown} 0
		 * @param {unknown} 1
		 */
		numbered_parameter: RequiredParams<'0' | '1'>
		/**
		 * H​e​l​l​o​ ​{​1​}​ ​{​0​}​!
		 * @param {unknown} 0
		 * @param {unknown} 1
		 */
		numbered_parameter2: RequiredParams<'0' | '1'>
	}
}

export type TranslationFunctions = {
	structural: {
		/**
		 * Create note
		 */
		CREATE_NOTE: () => LocalizedString
	}
	test: {
		/**
		 * Hello!
		 */
		no_parameter: () => LocalizedString
		/**
		 * Hello {name}!
		 */
		named_parameter: (arg: { name: string }) => LocalizedString
		/**
		 * Hello {first_name} {last_name}!
		 */
		named_parameter2: (arg: { first_name: string, last_name: string }) => LocalizedString
		/**
		 * Hello {0} {1}!
		 */
		numbered_parameter: (arg0: unknown, arg1: unknown) => LocalizedString
		/**
		 * Hello {1} {0}!
		 */
		numbered_parameter2: (arg0: unknown, arg1: unknown) => LocalizedString
	}
}

export type Formatters = {}
