# Reference:
# - https://tauri.app/v1/guides/building/cross-platform
# - https://github.com/tauri-apps/tauri-action/

name: 'publish'

# This will trigger the action on each push to the `release` branch.
on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: ./Structural-app
    steps:
      # Checkout the repository 
      - uses: actions/checkout@v4

      # Set up Node LTS and a cache for global npm/yarn/pnpm package data
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Set up Rust and a cache for the target/ folder
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Structural Note App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          tauriScript: 'npm run tauri'
          releaseDraft: true
          prerelease: false
